### ISSUE TITLE
Using an intent URL breaks the "New Post" button

### ISSUE THREAD

**Issue by gesteves** [bluesky-social/social-app#3043]
**Describe the bug**

Noticed this while poking at #3042: If you open an intent URL, like https://bsky.app/intent/compose?text=Test, and either send the post or discard it, the "New Post" button will stop working until you refresh the page. Pressing it shows the following error in the dev console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'routes')
    at LeftNav.tsx:203:22
    at Generator.next (<anonymous>)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at LeftNav.tsx:202:25
    at LeftNav.tsx:236:34
    at Generator.next (<anonymous>)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at LeftNav.tsx:235:23
    at onClick (PressResponder.js:310:13)
    at Object.Ne (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at jr (react-dom.production.min.js:105:68)
    at Ir (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at ul (react-dom.production.min.js:274:42)
    at Ve (react-dom.production.min.js:52:375)
    at Kr (react-dom.production.min.js:109:469)
    at Xt (react-dom.production.min.js:74:59)
    at qt (react-dom.production.min.js:73:73)
    at HTMLDivElement.r (helpers.ts:98:17)
```

**To Reproduce**

1. Click on https://bsky.app/intent/compose?text=Test
2. Composer opens with a populated text
3. Either post it, or discard it
4. Click "New Post"
5. Nothing happens (the error above should be visible in the dev console)

**Expected behavior**

The composer should open again.

**Screenshots**

N/A

**Details**

 - Platform: Desktop web (Arc 1.31.2 on macOS Sonoma 14.3.1, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`)
 - Platform version: Build version: 1.70.0; Platform: web
 - App version: N/A

**Additional context**

N/A

**Comment by haileyok** [comment]
Thank you!
