### ISSUE TITLE
App crashes when opening on Android

### ISSUE THREAD

**Issue by Gudine** [bluesky-social/social-app#5300]
**Describe the bug**
After the last update, the app crashes when opening on Android, displaying "Unfortunately, Bluesky has stopped"

**To Reproduce**

1. Open the app

**Expected behavior**

App opens without problems

**Details**

 - Platform: Android
 - Platform version: 6.0.1
 - App version: 1.91.0

**Additional context**

I tried using logcat (though I'm not too experienced with that) and this is what I found:

```
09-12 12:25:06.691 15173 15173 E AndroidRuntime: FATAL EXCEPTION: main
09-12 12:25:06.691 15173 15173 E AndroidRuntime: Process: xyz.blueskyweb.app, PID: 15173
09-12 12:25:06.691 15173 15173 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method deepCopy()Landroid/os/Bundle; in class Landroid/os/Bundle; or its super classes (declaration of 'android.os.Bundle' appears in /system/framework/framework.jar)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at expo.modules.video.VideoView$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at expo.modules.video.playbackService.ExpoVideoPlaybackService.setShowNotification(ExpoVideoPlaybackService.kt:47)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at expo.modules.video.playbackService.ExpoVideoPlaybackService.registerPlayer(ExpoVideoPlaybackService.kt:69)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at expo.modules.video.playbackService.PlaybackServiceConnection.onServiceConnected(PlaybackServiceConnection.kt:16)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1339)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1356)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-12 12:25:06.691 15173 15173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by AdrianoCahete** [comment]
> Platform version: 6.0.1

Android 6?

Android 6 has [API Level 23](https://developer.android.com/tools/releases/platforms#6.0), while Bsky app needs [API Level 34](https://github.com/bluesky-social/social-app/blob/1dc7ef137cb7a546b1c84c1e7304a4f74ea1e66b/app.config.js#L198).

Maybe this is the problem? Although, if this is the problem, I don't know why store let you install...

**Comment by haileyok** [comment]
23 should be fine, 34 is just the current target.

I have some in-flight work that I'm trying to get out today that should hopefully prevent this. Looks like a really small number of users are hitting this crash.

**Comment by Gudine** [comment]
The app doesn't crash anymore as of 1.91.1. Thanks!
